spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
logging:
  level:
    org.example.testdemo: debug
jwt:
  secret: "myStrongSecretKey1234567890abcdefg"
  expiration: 86400000
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucketName: my-bucket
