spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC
    username: school
    password: bBwRw6ZSDZrLcbPL
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.example.testdemo: info

jwt:
  secret: "ad23f8j23hr8923hr9823hr23hr8923hr9823hr23hr8923hr98"
  expiration: 86400000
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: my-bucket
# 文件上传配置
file:
  upload:
    server-url: http://localhost:8080
    avatar-upload-dir: uploads/avatars/
    avatar-access-path: /uploads/avatars/