spring:
  application:
    name: testdemo
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.testdemo.entity
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: warn

